config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:index, :show, :edit, :update]
  resources :notes, only: [:show, :create, :edit, :update, :destroy]

  root 'home#top'
  get '/about' => 'home#about'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
	has_many :likes

	validates :title, presence:true
	validates :content, presence:true, length:{maximum:140}
	validates :user_id, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :notes
  has_many :likes


  # 後の演習にてdeviseでnameを登録できるようにするまで、一時的にnameのバリデーションをコメントアウトしています
  # validates :name, presence: true
  # deviseのvalidatableによって以下と同じバリデーションが設定されるのでコメントアウトしています
  # validates :email, presence: true, uniqueness: true

  def set_image(file)
    if !file.nil?
      file_name = file.original_filename
      File.open("public/user_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      self.image = file_name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  include ApplicationHelper

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def default_url_options() {instanceId: '9b41acd950'}.merge(super) end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      # 変数@noteにNoteクラスのインスタンスを代入してください
      @note = Note.new
      # 変数@notesにNoteクラスのインスタンスの配列を降順で代入してください
      @notes = Note.all.order(created_at: :desc)
    else
      @message = "ようこそGatebookへ！"
    end
  end

  def about
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_note, only:[:show,:edit,:update,:destroy]

  #新規投稿用アクション
  def create
    #buileメソッドを用いてnotesコントローラのcreateアクションで、ユーザーと投稿を紐付ける
    @note = current_user.notes.build(note_params)

    if @note.save
      #保存成功時
      redirect_to note_path(@note.id), notice:"投稿が保存されました"
    else
      #保存失敗時
      @notes = Note.all.order(created_at: :desc)
      render "home/top"
    end
  end

  #詳細ページの表示用アクション
  def show
  end

  #投稿編集用アクション
  def edit
  end

  #更新用アクション
  def update
    @note.title = params[:note][:title]
    @note.content = params[:note][:content]
    @note.save

    if @note.update(note_params)
      #更新成功時
      redirect_to note_path(@note.id), notice:"投稿が更新されました"
    else
      #更新失敗時
      render :edit
    end
  end

  #削除用アクション
  def destroy
    @note.destroy

    redirect_to notes_path
  end

  #private before_action
  #指定idのレコードを取得する
  private def set_note
    @note = Note.find(params[:id])
  end

  private def note_params
    params.require(:note).permit(:title, :content)
  end

  private def correct_user
    note = Note.find(params[:id])
    #noteを投稿したユーザーを取得し、current_user?メソッドの引数に渡す
    if !current_user?(note.user)
      redirect_to root_path, alert: '許可されていないページです'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @notes = @user.notes
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #アップロードされた画像を受け取り、変数fileに代入
    file = params[:user][:image]

    #user.rbのインスタンスメソッドを呼び出す
    @user.set_image(file)

    if @user.update(user_params)
      #アップデートに成功したら
      redirect_to @user, notice: 'ユーザー情報が更新されました'
    else
      render :edit
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email)
  end

  def correct_user
    user = User.find(params[:id])
    if !current_user?(user)
      redirect_to root_path, alert: '許可されていないページです'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def image_for(user)
    if user.image
      #userのプロフィール画像を表示する
      image_tag "/user_images/#{user.image}", class: "profile_img"
    else
      #プロフィール画像が設定されていない場合、Defaule画像を表示する
      image_tag "wanko.png", class: "profile_img"
    end
  end
end

app/views/home/about.html.erb
<div class="container">
  <h1>Gatebookとは？</h1>
  <p>GatebookとはRuby on Railsというフレームワークを駆使した、
記事投稿SNSサービスです。
近況やつぶやきを投稿し、サービス上の友達と楽しくコミュニケーションできます。</p>
</div>

app/views/home/top.html.erb
<% if user_signed_in? %>
  <aside class="sidebar">
    <!-- renderメソッドを用いて、notes/_form.html.erbを呼び出してください -->
    <%= render "notes/form" %>
  </aside>
  <ul class="notes">
    <h2>投稿の一覧</h2>
    <!-- renderメソッドと@notesを用いて、notes/_note.html.erbを呼び出してください -->
    <%= render @notes %>
  </ul>
<% else %>
  <div class="top-wrapper">
    <%= image_tag "gatebook_cover.png" %>
    <div class="register-wrapper">
      <h1><%= @message %></h1>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-large register-btn" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gatebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="container">
      <div id="logo"><%= link_to "Gatebook", root_path %></div>
      <% if user_signed_in? %>
        <ul class="header-right">
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <!-- 表示するテキストで、現在ログイン中のユーザーのemailを表示してください -->
          <li><%= link_to current_user.email, current_user %></li>

          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>

        </ul>
      <% else %>
        <ul class="header-right">
          <li><%= link_to "概要", about_path %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>

        </ul>
      <% end %>
    </div>
  </header>

  <div class="container">
    <p class="alert alert-success"><%= notice %></p>
    <p class="alert alert-danger"><%= alert %></p>
    <%= yield %>
  </div>

  <div class="container">
    <footer class="footer">
      <div class="small">
        &copy; 2015 Progate, Inc.
      </div>
    </footer>
  </div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>

<% if @note.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
	<h2><%= @note.errors.count %>件のエラーがあります</h2>
	<ul>
		<% @note.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

タイトル
<%= f.text_field :title, class:"form-control title-field" %>
内容
<%= f.text_area :content, class:"form-control content-field" %>
<%= f.submit "保存", class:"btn primary-btn" %>
<% end %>

app/views/notes/_note.html.erb
<li>
	<%= image_for(note.user) %>
	<span class="user-name">
		<%= note.user.name %>
	</span>
	<span class="content">
		<%= link_to note.title, note_path(note.id) %>
	</span>
	
	<!-- 作成時間を表示するためのコード -->
	<span>
    <%= note.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
  </span>
</li>

app/views/notes/create.html.erb
<p><%= @note.title %></p>
<p><%= @note.content %></p>

app/views/notes/edit.html.erb
<h1>投稿を編集する</h1>

<%= render 'form' %>

app/views/notes/index.html.erb
<h1>投稿の一覧</h1>
<ul class="notes">
	<%= render @notes %>
</ul>

app/views/notes/new.html.erb
<h1>新規投稿する</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<!-- 投稿成功メッセージの表示 -->
<p id="notice" class="alert alert-success">
	<%= notice %>
</p>

<h2>タイトル</h2>
<p><%= @note.title %></p>
<h2>内容</h2>
<p><%= @note.content %></p>

<% if current_user?(@note.user) %>
	<%= link_to "編集", edit_note_path(@note.id), class:'btn edit-btn' %>
	<%= link_to "削除", note_path, method: "delete", class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div class="alert alert-danger">
 <p><%= @user.errors.count %>件のエラーがあります。</p>

 <ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

名前
<%= f.text_field :name, class: "form-control name-field" %>

メールアドレス
<%= f.text_field :email, class: "form-control email-field" %>

プロフィール画像
<%= f.file_field :image, class: "form-control image-field" %>

<%= f.submit "保存", class:"btn primary-btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= render 'form' %>

<%= link_to 'ユーザー一覧へ', users_path %>

app/views/users/index.html.erb
<h1 class="heading">ユーザー一覧</h1>

<ul class="user-list">
  <% @users.each do |user| %>
  <li>
    <!-- user_helperのimage_forヘルパーを呼び出してユーザーの画像を表示する -->
    <%= image_for(user) %>

    <%= link_to user.name, user %> |
    <%= user.email %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>新規ユーザー作成</h1>

<%= render 'form' %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<aside class="sidebar">
	<section>
		<span class="label">プロフィール画像</span>
		<h3 class="user-info">
			<%= image_for(@user) %>
		</h3>
	</section>

	<section>
		<span class="label">ユーザー</span>
		<h3 class="user-info"><%= @user.name %></h3>
	</section>

	<section>
		<span class="label">メールアドレス</span>
		<h3 class="user-info"><%= @user.email %></h3>
	</section>

	<% if current_user?(@user) %>
		<section>
			<small><%= link_to 'プロフィールを編集', edit_user_path(@user) %></small>
		</section>
	<% end %>

</aside>

<ul class="notes">
	<%= render @notes %>
</ul>